# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-27 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20160827_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='tyre_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='acceleration',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='front_brake_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='rear_brake_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='turning_radius',
            field=models.FloatField(),
        ),
    ]
