# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-03 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20160903_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='acceleration',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='bottle_holder',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='country_of_assembly',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='country_of_manufacture',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='cylinders',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive_type',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='car',
            name='emission_control_system',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='emission_norm_compliance',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_description',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_displacement',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='foldable_rear_seat',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='front_brake_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='front_suspension',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(blank=True, choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel')], max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_supply',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='car',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='gearbox',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='keyword',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='manufacturer',
            field=models.CharField(blank=True, choices=[('Audi', 'Audi'), ('Maruti-Suzuki', 'Maruti-Suzuki'), ('Tata Motors', 'Tata Motors'), ('Hyundai', 'Hyundai'), ('Honda', 'Honda'), ('Volkswagen', 'Volkswagen'), ('Toyota', 'Toyota'), ('Mahindra', 'Mahindra'), ('Renault', 'Renault'), ('Fiat', 'Fiat'), ('Chevrolet', 'Chevrolet'), ('Ford', 'Ford'), ('KIA', 'KIA'), ('Porsche', 'Porsche')], max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='parking_sensors',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='power',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='rear_brake_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='rear_suspension',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='shock_absorbers_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='steer_type',
            field=models.CharField(blank=True, choices=[('Rack and Pinion', 'Rack and Pinion')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='top_speed',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='torque',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='turning_radius',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(blank=True, choices=[('Hatchback', 'Hatchback'), ('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Crossover', 'Crossover'), ('MUV', 'MUV'), ('Mini SUV', 'Mini SUV')], max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='valves_per_cylinder',
            field=models.IntegerField(blank=True),
        ),
    ]
