# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-14 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_auto_20160914_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='manufacturer',
            field=models.CharField(blank=True, choices=[('Audi', 'Audi'), ('Maruti-Suzuki', 'Maruti-Suzuki'), ('Tata Motors', 'Tata Motors'), ('Hyundai', 'Hyundai'), ('Honda', 'Honda'), ('Volkswagen', 'Volkswagen'), ('Toyota', 'Toyota'), ('Mahindra', 'Mahindra'), ('Renault', 'Renault'), ('Fiat', 'Fiat'), ('Chevrolet', 'Chevrolet'), ('Ford', 'Ford'), ('Porsche', 'Porsche'), ('Nissan', 'Nissan'), ('Datsun', 'Datsun'), ('Jaguar', 'Jaguar'), ('Mercedes-Benz', 'Mercedes-Benz'), ('BMW', 'BMW'), ('Land Rover', 'Land Rover')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='manufacturer',
            field=models.CharField(blank=True, choices=[('Audi', 'Audi'), ('Maruti-Suzuki', 'Maruti-Suzuki'), ('Tata Motors', 'Tata Motors'), ('Hyundai', 'Hyundai'), ('Honda', 'Honda'), ('Volkswagen', 'Volkswagen'), ('Toyota', 'Toyota'), ('Mahindra', 'Mahindra'), ('Renault', 'Renault'), ('Fiat', 'Fiat'), ('Chevrolet', 'Chevrolet'), ('Ford', 'Ford'), ('Porsche', 'Porsche'), ('Nissan', 'Nissan'), ('Datsun', 'Datsun'), ('Jaguar', 'Jaguar'), ('Mercedes-Benz', 'Mercedes-Benz'), ('BMW', 'BMW'), ('Land Rover', 'Land Rover')], max_length=50),
        ),
    ]
