# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-15 14:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_auto_20160915_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdrive',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.UserProfile'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.UserProfile'),
        ),
        migrations.AlterField(
            model_name='testdrive',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 15, 20, 15, 12, 616956)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 15, 20, 15, 12, 615952)),
        ),
    ]
