# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-15 14:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0018_auto_20160915_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdrive',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 15, 20, 16, 4, 953767)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 15, 20, 16, 4, 953267)),
        ),
    ]
