# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-16 02:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0019_auto_20160915_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_premium',
            new_name='is_dealer',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='user',
        ),
        migrations.AddField(
            model_name='dealer',
            name='user_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.UserProfile'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='manufacturer',
            field=models.CharField(choices=[('Audi', 'Audi'), ('Maruti-Suzuki', 'Maruti-Suzuki'), ('Tata Motors', 'Tata Motors'), ('Hyundai', 'Hyundai'), ('Honda', 'Honda'), ('Volkswagen', 'Volkswagen'), ('Toyota', 'Toyota'), ('Mahindra', 'Mahindra'), ('Renault', 'Renault'), ('Fiat', 'Fiat'), ('Chevrolet', 'Chevrolet'), ('Ford', 'Ford'), ('Porsche', 'Porsche'), ('Nissan', 'Nissan'), ('Datsun', 'Datsun'), ('Jaguar', 'Jaguar'), ('Mercedes-Benz', 'Mercedes-Benz'), ('BMW', 'BMW'), ('Land Rover', 'Land Rover')], max_length=50),
        ),
        migrations.AlterField(
            model_name='testdrive',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 16, 7, 40, 3, 151879)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='DOB',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 16, 7, 40, 3, 150878)),
        ),
    ]
