# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-16 02:18
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0020_auto_20160916_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testdrive',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 16, 7, 48, 15, 495691)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 16, 7, 48, 15, 494668)),
        ),
    ]
