# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-16 02:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0021_auto_20160916_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdrive',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 16, 7, 48, 15, 651565)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 16, 7, 48, 15, 650500)),
        ),
    ]
